import os
import random
import shutil
from pathlib import Path
from src.config import PROJECT_ROOT, DATA_DIR

def prepare_ocr_dataset(train_ratio: float = 0.8):
    """
    Splits the labeled character crops in data/character_labeling/ into 
    train and validation sets for YOLOv8 OCR training.
    """
    base_dir = DATA_DIR / "character_labeling"
    
    # We expect images and labels to be in the same folder 'character_labeling'
    # as generated by the crop_characters script.
    if not base_dir.exists():
        print(f"[ERROR] Directory not found: {base_dir}")
        return

    # Find all images
    valid_exts = {'.jpg', '.jpeg', '.png'}
    image_files = sorted([p for p in base_dir.iterdir() if p.suffix.lower() in valid_exts])
    
    if not image_files:
        print("[ERROR] No images found in character_labeling folder.")
        return

    # Filter only those that have a corresponding .txt label
    labeled_images = []
    for img_p in image_files:
        label_p = img_p.with_suffix('.txt')
        if label_p.exists():
            labeled_images.append(img_p)

    if not labeled_images:
        print("[ERROR] No labeled images found (missing .txt files).")
        return

    print(f"Found {len(labeled_images)} labeled character crops.")

    # Shuffle and split
    random.seed(42)
    random.shuffle(labeled_images)
    split_idx = int(len(labeled_images) * train_ratio)
    
    train_files = labeled_images[:split_idx]
    val_files = labeled_images[split_idx:]

    # Create directory structure for YOLO
    yolo_ocr_dir = DATA_DIR / "yolo_ocr_dataset"
    for split in ['train', 'val']:
        (yolo_ocr_dir / split / 'images').mkdir(parents=True, exist_ok=True)
        (yolo_ocr_dir / split / 'labels').mkdir(parents=True, exist_ok=True)

    # Move files
    def copy_split(files, split_name):
        for img_p in files:
            label_p = img_p.with_suffix('.txt')
            # Copy Image
            shutil.copy(img_p, yolo_ocr_dir / split_name / 'images' / img_p.name)
            # Copy Label
            shutil.copy(label_p, yolo_ocr_dir / split_name / 'labels' / label_p.name)

    print("Copying files to training structure...")
    copy_split(train_files, 'train')
    copy_split(val_files, 'val')

    # Generate data.yaml (36 classes: 0-9, A-Z)
    names = {
        0: '0', 1: '1', 2: '2', 3: '3', 4: '4', 5: '5', 6: '6', 7: '7', 8: '8', 9: '9',
        10: 'A', 11: 'B', 12: 'C', 13: 'D', 14: 'E', 15: 'F', 16: 'G', 17: 'H', 18: 'I', 19: 'J',
        20: 'K', 21: 'L', 22: 'M', 23: 'N', 24: 'O', 25: 'P', 26: 'Q', 27: 'R', 28: 'S', 29: 'T',
        30: 'U', 31: 'V', 32: 'W', 33: 'X', 34: 'Y', 35: 'Z'
    }

    import yaml
    yaml_content = {
        'path': str(yolo_ocr_dir.absolute()),
        'train': 'train/images',
        'val': 'val/images',
        'names': names
    }

    yaml_path = yolo_ocr_dir / "ocr_chars.yaml"
    with open(yaml_path, 'w') as f:
        yaml.dump(yaml_content, f, sort_keys=False)

    print(f"\n[SUCCESS] OCR Dataset ready at: {yolo_ocr_dir}")
    print(f"YAML config saved to: {yaml_path}")

if __name__ == "__main__":
    prepare_ocr_dataset()
